# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 03:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(default='Bhairav Offset', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default=datetime.datetime(2016, 2, 28, 3, 4, 54, 764990, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
