# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20160228_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('attendance', models.FileField(upload_to='attendanceSheet')),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(),
        ),
    ]
